.\"#ident	"@(#)ccsman:g5/values	1.2"
'\"macro stdmacro
.nr X
.if \nX=0 .ds x} VALUES 5 "630 MTG"  "\&"
.TH \*(x}
.SH NAME
values \- machine-dependent values
.SH SYNOPSIS
.B #include <ccs/values.h>
.SH DESCRIPTION
This file contains a set of manifest constants,
conditionally defined for particular processor architectures.
.P
The model assumed for integers is two's complement binary,
where the sign is represented by the value of the high-order bit.
.P
.TP 20
.RI \s-1BITS\s0( type\^ )
The number of bits in a specified type (e.g., int).
.TP 20
.SM
HIBITS
The value of a short integer with only the high-order bit set
(0x8000).
.TP 20
.SM
HIBITL
The value of a long integer with only the high-order bit set
(0x80000000).
.TP 20
.SM
HIBITI
The value of a regular integer with only the high-order bit set
(the same as \s-1HIBITS\s0). 
.TP 20
.SM
MAXSHORT
The maximum value of a signed short integer
(0x7FFF \(== 32767).
.TP 20
.SM
MAXLONG
The maximum value of a signed long integer
(0x7FFFFFFF \(== 2147483647).
.TP 20
.SM
MAXINT
The maximum value of a signed regular integer
(the same as \s-1MAXSHORT\s0).
.TP 30
.SM
MAXFLOAT, LN_MAXFLOAT
The maximum value of a single-precision floating-point number,
and its natural logarithm.
.TP 30
.SM
MAXDOUBLE, LN_MAXDOUBLE
The maximum value of a double-precision floating-point number,
and its natural logarithm.
.TP 30
.SM
MINFLOAT, LN_MINFLOAT
The minimum positive value of a single-precision floating-point number,
and its natural logarithm.
.TP 30
.SM
MINDOUBLE, LN_MINDOUBLE
The minimum positive value of a double-precision floating-point number,
and its natural logarithm.
.TP 20
.SM
FSIGNIF
The number of significant bits in the mantissa of a single-precision
floating-point number.
.TP 20
.SM
DSIGNIF
The number of significant bits in the mantissa of a double-precision
floating-point number.
.SH FILES
$DMD/include/ccs/values.h
.SH "SEE ALSO"
math(5).
.Ee
