.TH ABS 3L "630 MTG"
.SH NAME
abs \- return integer absolute value
.SH SYNOPSIS
.B int abs (i)
.br
.B int i;
.SH DESCRIPTION
.I abs\^
returns
the absolute value of its integer operand.
.SH SEE ALSO
floor(3M).
.SH WARNING
In two's-complement representation,
the absolute value of the negative integer with largest magnitude is undefined.
.Ee
