.ds ZZ DEVELOPMENT PACKAGE
.TH FONTNAME 3R "630 MTG"
.XE "fontname()"
.SH NAME
fontname \- get the name of a font
.SH SYNOPSIS
.B #include <dmd.h>
.br
.B #include <font.h>
.sp
.B char \(**fontname (f)
.sp
.B Font \(**f;
.SH DESCRIPTION
The
.I fontname
function returns a pointer to the name of the font in the font cache that
.I f
points to. If
.I \(**f
is not in the font cache,
.I fontname
returns a null character pointer.
.PP
.SH SEE ALSO
fontrequest(3R), fontsave(3L), infont(3R/3L), structures(3R).
