.TH ISMPX 3R "630 MTG"
.XE "ismpx()"
.SH NAME
ismpx \- test if connected to a multiplexed host
.SH SYNOPSIS
.B int ismpx ( );
.SH DESCRIPTION
The
.I ismpx
function
tests if the application program is connected to a host via a multiplexed
connection.
If so, a 1 is returned;
otherwise, 0 is returned.
.I Layers
is one example of a multiplexed connection protocol.
.PP
.SH SEE ALSO
attach(3R), local(3R), peel(3R).
.br
layers(1) in \f2UNIX System V Release 3 User's Reference Manual\f1.
.br
layers(1) in \f25620 Dot-Mapped Display Reference Manual\f1.
