.ds ZZ DEVELOPMENT PACKAGE
.TH JMOVE 3L "630 MTG"
.XE "jmove()"
.XE "jmoveto()"
.SH NAME
jmove, jmoveto \- move current window point on display, relative or absolute
.SH SYNOPSIS
.B #include <dmd.h>
.sp
.B void jmove (p)
.PP
.B void jmoveto (p)
.PP
.B Point p;
.SH DESCRIPTION
The
.I jmove
function
moves the current window point by the relative vector
.I p
which is in window coordinates.
.PP
The
.I jmoveto
function
sets the current window point to the absolute location
.I p
which is in window coordinates.
.SH EXAMPLE
See the example in
.IR jsegment (3L).
.SH SEE ALSO
jsegment(3L), moveto(3L), structures(3R), transform(3R/3L).
