.ds ZZ DEVELOPMENT PACKAGE
.TH MSGBOX 3R "630 MTG"
.XE "msgbox()"
.SH NAME
msgbox \- put up a message in a box
.SH SYNOPSIS
.B int msgbox (s,...)
.br
.B char \(**s;
.SH DESCRIPTION
The
.I msgbox
function
puts up a message in a box that tracks with the mouse.
Its argument(s) are strings terminated by the argument (char *)0.
Each string is placed on a separate line in the message box and
is centered and displayed with the medium font.
The message box replaces the mouse cursor and follows the mouse
around the screen until a button is depressed.
.PP
If the first argument to
.I msgbox
is (char *)0,
a message box with the message "No Memory"
is displayed.
.PP
If there is no memory for displaying the given message,
.I msgbox
puts up a message box with the message "No Memory" and
returns the value 0.
Otherwise, it returns 1.
