.ds ZZ DEVELOPMENT PACKAGE
.TH RECTCLIP 3R "630 MTG"
.XE "rectclip()"
.SH NAME
rectclip \- clip a Rectangle to another Rectangle
.SH SYNOPSIS
\f3
#include <dmd.h>
.sp
int rectclip (rp, s)
.br
Rectangle \(**rp, s;\f1
.SH DESCRIPTION
The
.I rectclip
function
clips the Rectangle pointed to by
.I rp
so that it is completely contained within the Rectangle
.IR s .
The return value is 1 if any part of
.I *rp
is within \f2s\f1.
Otherwise, the return value is 0 and
.I *rp
is unchanged.
.SH EXAMPLE
See the example for
.IR newrect (3R).
.SH SEE ALSO
newrect(3R).
