.ds ZZ DEVELOPMENT PACKAGE
.TH RINGBELL 3R "630 MTG"
.XE "ringbell()"
.XE "click()"
.SH NAME
ringbell, click \- ring, click the 630 MTG
.SH SYNOPSIS
.ft B
void ringbell ( )
.sp
\f3void click ( )\f1
.ft R
.SH DESCRIPTION
The
.I ringbell
function rings the bell on the 630 MTG.
.PP
The
.I click
function makes the 630 MTG click as if a key has been depressed.
.SH EXAMPLE
See the example in
.IR polygon (3L).
