.\"#ident	"@(#)ccsman:g3c/swab	1.2"
'\"macro stdmacro
.nr X
.if \nX=0 .ds x} SWAB 3L "630 MTG" "\&"
.TH \*(x}
.SH NAME
swab \- swap bytes
.SH SYNOPSIS
.B void swab (from, to, nbytes)
.br
.B char \(**from, \(**to;
.br
.B int nbytes;
.SH DESCRIPTION
.I swab\^
copies
.I nbytes\^
bytes pointed to by
.I from\^
to the array pointed to by
.IR to ,
exchanging adjacent even and odd bytes.
.I Nbytes\^
should be even and non-negative.
If
.I nbytes\^
is odd and positive,
.I swab\^
uses
.IR nbytes \-1
instead. If
.I nbytes\^
is negative,
.I swab\^
does nothing.
.Ee
