.ds ZZ DEVELOPMENT PACKAGE
.TH WHATHOST 3R "630 MTG"
.XE "whathost()"
.SH NAME
whathost \- determine host connection
.SH SYNOPSIS
.B int whathost ( ) 
.sp
.SH DESCRIPTION
The
.I whathost
function
returns an identifier for the host to which the process is connected.
This value is most useful as an argument to
.IR setupval .
The value -1 is returned if the process is local.
.SH SEE ALSO
local(3R), setupval(3R).
