.TH DMDDEMO 1 "630 MTG"
.SH NAME
dmddemo - demonstrations available on the 630 MTG
.SH SYNOPSIS
\fBdmddemo\fR [options]
.SH DESCRIPTION
The \fIdmddemos\fR are graphical demonstration programs that run on the 630 MTG.
All programs will become local unless they are downloaded into a window
which is the last window connected to a host.
Exiting each program can be done by typing 'q' when that window is current
or by deleting the window.
Typing \fIdmddemo\fR
with no options gives you a list of demonstrations available.
.sp 2
Demos include at least these:
.nf
.sp
    \fBball\fR         A bouncing ball
.sp 
    \fBbounce\fR     Ricocheting lines. Button 1 controls speed.
.sp
    \fBclock\fR       Displays face of clock with moving hands in
                  addition to a digital time display.
.sp
    \fBdoodle\fR     An interactive doodler. Button 1 draws and 
                  button 2 erases.
.sp
    \fBrose\fR         Rotates trigonometric figures to produce various
                  flower shapes.
.sp
    \fBstar\fR         Interactive drawing. Button 1 draws and button 2 erases.
