.TH MC68CPRS 1 "630 MTG"
.SH NAME
mc68cprs \- compress a MC68000 object file
.SH SYNOPSIS
.B mc68cprs
.RB [ \-pv ]
infile outfile
.SH DESCRIPTION
The 
.I mc68cprs
command
reduces the size of a Motorola 68000 object file,
.IR infile ,
by removing duplicate structure and union descriptors.
The reduced file,
.IR outfile ,
is produced as output.
.PP
The options are:
.PP
.TP 6
.B \-p
Prints statistical messages including:
.sp
.RS 12
total number of tags
.br
total duplicate tags
.br
total reduction of 
.IR infile .
.RE
.PP
.TP 6
.B \-v
Prints verbose error messages if error condition occurs.
.SH EXAMPLE
.ft CW
	mc68cprs dmda.out sm3b
.ft R
.SH SEE ALSO
mc68strip(1).
